### ISSUE TITLE
Design Question - Should we call it "Errors Found?"

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#28]
@tomcalabrese 

Check it out: http://s4.brainpop.com/games/quill/

Right now in the BrainPOP app we are using a counter for errors found. It feels a bit weird though, because editing wrong words causes the counter to go up. It implies that you found the error, when in reality you didn't. 

We could call it "Words Corrected" which would better reflect that your edits are not actually the correct edits. 

The problem with this system, however, is that it is no longer clear that "Words Found: 0 of 9" implies that there are 9 errors.

**Comment by tomcalabrese** [comment]
I think how Will has it "Words Changed" makes the most sense, because it doesn't imply that the words changed are correct or not. "Words Corrected" is similar to "Errors Found" and doesn't fix the problem, but "Words Changed" does. 

Maybe we reiterate how many errors they have to find in the instructions. "Proofread the passage below, making sure that all the commonly confused words are spelled correctly. Find 13 errors in the passage below."

I showed it to a few people in the bat haus and they got it right away, but they're also not in 3rd grade.

**Comment by petergault** [comment]
Okay cool. Let's stick with words changed and include the number of errors in the instructions.

**Comment by wlaurance** [comment]
What about the button text when the student is reviewing their results. The button in the wireframes says 'Next Error'. It seems a little strange if they are going to a correct response next. Should this be considered as well?

**Comment by petergault** [comment]
Next Correction maybe? Next Edit?

**Comment by RyanNovas** [comment]
I like next edit -- if they made an inappropriate edit, we can say "unrecognized change" (probably better than introduced error, since often they are acceptable), and if not we can just go to the next text box that should've been corrected

**Comment by tomcalabrese** [comment]
Agreed, Next Edit.
