### ISSUE TITLE
brainpop comments

### ISSUE THREAD

**Issue by ccowdery** [empirical-org/Quill-Grammar#30]
Bug # 1
In the princess and the turtle story, there are no parentheses in the text encapsulating the errors, and yet the directions still state that the students should remember to delete them before pressing submit.

Note: Since we are electing to pivot towards the type 1 word model, rather than the whole sentence model, having an auto select feature that would select the whole word when its clicked on, including the parentheses errors, so that its 1 click to select the error, then type the correct word, then click to blank space to finish the change.

There is also a possibility that we would want to put in a "revert to native text" function on the stories, so that in case students are working on a passage and they get over their heads, they can press the revert button to set the whole passage back to its starting text without any of their additions.

BUG # 2
When I finished the story, it gave an incorrect text saying I found 5 of 1 errors, it always incorrectly lists amount of errors found.

![bug 1](https://cloud.githubusercontent.com/assets/6025451/6763704/8f876d5c-cf5f-11e4-9fb9-2632e670d177.png)

NOTE:  I find pages that the dialog box moves around on to be somewhat disctracting, so an idea would be to make the error box on the app stay stationary, while the page moves around it so the student doesn't have to move the mouse to click the next button again, not an urgent change.

BUG # 3
The grammatical concepts listed on the errors on the errors found all say Grammar Concept TODO

![image](https://cloud.githubusercontent.com/assets/6025451/6763721/08b565a8-cf60-11e4-9c7f-490b4b899b14.png)

NOTE: I think that the "check work" button should disappear after you click it once and it takes you through the errors. Having it there at the bottom, once the student is reviewing their work on the story, can only confuse the student. Once the review phase of the story has started, the button need to disappear or  be renamed.

BUG # 4
Custom results page does not load at all, just gives the text "Custom Results Page"

![image](https://cloud.githubusercontent.com/assets/6025451/6763737/7b54851c-cf60-11e4-86f6-7b51f3e92a43.png)

NOTE: there might be a button that takes you back to back to the home page at BrainPop showing the Quill landing page, but if the results page does not load, then there is no way to get back. 

NOTE # 2: Quill does not show up if the word is searched on the brainpop search bar right above our page. We need to get that fixed asap, really urgent.

BUG # 5
The correct answer to sentence questions after the paragrpaph has been completed do not appear.
It reads instead, "Incorrect Answer: correct answer here"

![image](https://cloud.githubusercontent.com/assets/6025451/6763748/11904278-cf61-11e4-9574-3ab8933c53c5.png)

BUG # 6
Some of the spacing of errors is incorrect, where there are too many spaces before the slash (choice 1 / choice 2) is correct, but we have an extra space before the (near / on) error, as well as some other errors, in the Apollo 8 story.

![image](https://cloud.githubusercontent.com/assets/6025451/6763769/48631cc0-cf62-11e4-83d0-8db0d10b236d.png)

**Comment by wlaurance** [comment]
@ccowdery Thanks! Yeah as you might have figured some of these are still TODOs

**Comment by wlaurance** [comment]
Bug 6 and Bug 1 will be fixed with changes to the underlying data cc/ @petergault @RyanNovas

**Comment by RyanNovas** [comment]
*Proofreading*

- [ ] "View Results" button does not work after getting every error

- [ ] "View Results" page is only showing one concept for "Princes and Turtle" (but this may be an problem with how we mapped out the concepts rather than the app)

- [ ] If no text is selected, backspace brings user to previous screen. The paragraph breaks are large, so this becomes problematic. We should either autoselect text, or turn these paragraph breaks into textual areas.

- [ ] Edits that are made without hitting "check results" do not persist.

- [ ] It says "you must find at least 50% of errors" However, finding them isn't enough -- they need to be solved. Let's change "find" to "solve" or just make it be "you must make x edits". 

- [ ] Instead of "Words Changed" in the counter, I think it should just say "Edits Made" this is for two reasons. 1) Edit is the correct terminology in proofreading. 2) Not all edits will be to words, some may be changing punctuation, etc..

- [ ] Similar to the above item, in the review view, it should be "Correct Edit" rather than "Correct Word"

- [ ] If an entire word is deleted, it does not count on the counter.

- [ ] The review counter counts all edits. While it makes sense for the primary one to do so, I think that the review one should only count edits to inserted errors (i.e. max out at X of X errors).
![screen shot 2015-03-26 at 5 52 58 pm](https://cloud.githubusercontent.com/assets/6655439/6857976/15673e54-d3e1-11e4-9b30-4a94f90a8874.png)



*Sentence Writing*
- [ ] If I click "Check Work" with nothing entered, nothing happens. There should be a notification that says something like "You must enter a sentence for us to check."

- [ ] In the sentence writing section, the sentence can be cut and pasted. We got rid of this functionality in the original app.

- [ ] After two wrong answers, it says "Next Activity" It should says "Next Problem" or "Next Challenge" or something else. The activity is the whole experience.


*Results Page*
- [ ] We should indicate the typing errors on the results page. Right now, we point out that students have made them, but there is no follow up.

- [ ] On the results page, the grammar concepts are broken up for passage proofreading, but not sentence writing. Not sure if that was the plan, but I think it should be in both.

- [ ] "How do we grade?" on top of the results page does not link anywhere

**Comment by petergault** [comment]
This is optional: 
 Edits that are made without hitting "check results" do not persist.

**Comment by wlaurance** [comment]
" "View Results" page is only showing one concept for "Princes and Turtle" (but this may be an problem with how we mapped out the concepts rather than the app)"

For Passages, it seems like the Princes and Turtle is the only one of the three that isn't correct.

For Sentence Writings, I'm not using the correct thing.

**Comment by wlaurance** [comment]
I've made the first word be autofocused.

**Comment by wlaurance** [comment]
Went with, 'You must make at least X edits', where x = Math.floor((number of errors) / 2)

**Comment by wlaurance** [comment]
This warning message for a blank sentence goes away after three seconds. If this is a desired behavior we can reproduce for all of the try it again errors.

**Comment by wlaurance** [comment]
```
conceptCategory: "Nouns & Pronouns"conceptClass: "Grammar Concepts"conceptTag: "Pronoun Shift: Singular"
```

Here is what I have for the choices to show in the results page for sentence writings. It should either be Category or Tag I believe @RyanNovas or @petergault

**Comment by wlaurance** [comment]
@RyanNovas and @petergault What should we do for ""How do we grade?" on top of the results page does not link anywhere", There isn't anything in the designs. If we are following suit with the other fonts like this one, I think this is a hover and show a tooltip? @tomcalabrese

**Comment by wlaurance** [comment]
@RyanNovas: Can you elaborate a little more on this one?

"We should indicate the typing errors on the results page. Right now, we point out that students have made them, but there is no follow up."

Thanks!

**Comment by wlaurance** [comment]
As of this comment, the checked marked tasks have been deployed to production and staging. Along with a data update to production.

**Comment by wlaurance** [comment]
We are using the rule number title for the grammatical concept in the tooltip popup. 

After the admin interface is up, we will revisit this by adding in the grammatical concept into the data model for the proofreading passage error syntax.

**Comment by RyanNovas** [comment]
*Passage Proofreading*

[ ] Edits that are made without hitting "check results" do not persist. **Optional. Let me know if any of these projects are particularly tricky.**

[ ] If an entire word is deleted, it does not count on the counter.

[ ] Not all edits from PR's have been made to content -- specifically "them-" is still in activity.

[ ] Still says Grammar Concept: TODO

*Sentence Writing*
[ ] Still showing "Correct Answer: Correct answer here

Results Page

[ ] We should indicate the typing errors on the results page. Right now, we point out that students have made them, but there is no follow up. IGNORE THIS. WE WILL ADD AT A LATER DATE

[ ]  On the results page, the grammar concepts are broken up for passage proofreading, but not sentence writing. Not sure if that was the plan, but I think it should be in both.

[ ] "How do we grade?" on top of the results page does not link anywhere

**Comment by petergault** [comment]
@wlaurance 
> {
  conceptCategory: "Nouns & Pronouns",
  conceptClass: "Grammar Concepts",
  conceptTag: "Pronoun Shift: Singular"
}
Here is what I have for the choices to show in the results page for sentence writings. It should either be Category or Tag I believe @RyanNovas or @petergault

We want to show the tag here, not the category. The category is used on the LMS to organize the data.

**Comment by RyanNovas** [comment]
*Content Changes*
- [ ] Katya suggests adding females. We could do *The Princess and the Turtle* to make it more feminine.

- [ ] The bushes preposition question (in / under) is ambiguous

- [ ] BrainPOP says: In the Apollo 8 passage, the word “with” is the default in the pictured sentence. However, “with” is a grammatically correct option in this sentence (having the same meaning as “even
with” or “despite”).

**Comment by wlaurance** [comment]
I signed up for Browser stack to try it on IE9. I'm not sure what's going on. It doesn't seem to like
any of our code here.

![screenshot - 03312015 - 11 15 09 am](https://cloud.githubusercontent.com/assets/1059214/6926305/32ff2ba4-d79a-11e4-96a8-43e2b35fba63.png)

**Comment by petergault** [comment]
I'm going to close this issue and create a new one if that's allright Will.

**Comment by wlaurance** [comment]
Yes, this is issue has been worked to death! :) Closing now
