### ISSUE TITLE
Quill Grammar - Homepage for Content Editor

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#80]
**This can just be an ugly page that leads to two links. One for activities, one for CMS (concepts).**

This issues introduces the homepage and overall UX for the Quill Grammar app. The focus right now is on the related issue about the activity editor. 

# Page 1: Select Tool
(note this page can be skipped for now. I'm including it to give a sense of the final UX.)
This page loads the partner app in the iframe.

See https://github.com/empirical-org/Empirical-Core/issues/820
![0 1 _activities_editor 2](https://cloud.githubusercontent.com/assets/3667179/8564255/9d3ab6bc-24fe-11e5-8821-1403aeccb9a3.png)

# Page 2: Homepage for Quill Grammar Editor 
Narrative: this page loads as either an iframe or a page re-direct from the LMS 

![screen shot 2015-07-07 at 11 12 35 pm](https://cloud.githubusercontent.com/assets/3667179/8564448/e8797d0a-2500-11e5-8efa-690f191b2a9a.png)

- [ ] grammar.quill.org/#/activity_editor
- [ ] load number of activities
- [ ] load number of concepts
- [ ] load number of questions (rule_questions)
- [ ] select activities to edit. 
- [ ] select materials to edit. 

Link: https://moqups.com/gault8121/J7pltM9L/p:abe750bb0

# Overall Architecture

![path architecture](https://cloud.githubusercontent.com/assets/3667179/8564607/a136250e-2502-11e5-96a1-e71e5f9d42a5.png)

https://moqups.com/gault8121/J7pltM9L/p:a45c0b391

**Comment by marcellosachs** [comment]
@petergault looks good. This can be implemented so any of these pages exists on either the LMS or on Quill-Grammar, since any data can be GET-ed or POST-ed in either direction. One design principle we may want to employ for now is the following : If UI page P involves (POST, PUT, DESTROY) requests to site1 and (GET) requests to site2, then build the page in site1. In other words, reduce the amount of POST, PUT, DESTROY requests that have to be made over the api. Using this convention might make it simpler for developers to know off the bat on which app a page is likely located. There might be edge cases where POST, PUT, DESTROY requests are made to two different places, so we'll have to handle those on a case-by-case basis. 

Under this convention, (2.2, 2.2.1, 2.2.X) would be on the LMS, (2.3, 2.3.1, 2.3.X, 2.3.2) would be on the LMS, and 2.3.2 would be on QG.

Open to other ideas on this, this is my first impression of what a sensible convention might be. 
But whether or not this convention is employed, this general design outlined in the issue where sites make GET, POST, PUT, DESTROY to each other will definitely work.

**Comment by petergault** [comment]
Replaced by newer issues.
