### ISSUE TITLE
Quill LMS / App JSON - Create new Activity

### ISSUE THREAD

**Issue by petergault** [empirical-org/Quill-Grammar#94]
```
{
   “title”: “A Great Title”,
   “description”: “Awesome Description long long long”,
   “section”: “QcEM4Upz9CO6oD4YKcmJ4g”,
   “topic”: “QcEM4Upz9CO6oD4YKcmJ4e”,
   “topic_category”: “QcEM4Upz9CO6oD4YKcmJ49”
}
```

**Comment by marcellosachs** [comment]
Some notes - 
Any time you use an id (or 'uid') to refer to an item in a database, it is not necessary to also supply any other features of that item (such as name, title, etc). So we should be able to not include the title of the standard_level, standard, and theme in the data.

What I was talking about over the phone in regards the 0 level concepts - 
I think I prefer a system where the LMS queries an app for the 0 level concepts associated to a particular activity when it needs them, instead of hard coding those associations into the LMS database. This would not require the LMS to know anything about the internal structure of any third party app. The request would only include the id of an activity, and the lms would only know that it gets the 0 level concepts associated to that activity back from that request (it doesnt know anything about how the app associates its activities to 0 level concepts, whether its through questions or through synonyms, etc.)

In general I prefer using more queries to gather implicit information than using less queries that gather explicitly hard coded, redundant information. This is because the latter approach requires updates that propagate to every place that the information is stored redundantly. In this scenario anytime you remove a query that has to be made, you make the update process more complex. The update process may not seem that complex on first glance, but in my experience update processes that seem relatively simple in terms of their conceptual explanation turn out to very complicated, introduce bugs, and take up development time (thinking back to my experience with hard-coding the is_final_score property into activity_sessions).

The update process in question is the following - if at some point one decides that a question in Quill-Grammar is not associated to concept1 but is instead associated to concept2, then Quill-Grammar will have to 
1) identify all the activities that involve that question
2) make a post request to the LMS to update the associations on the LMS of the activity to its concepts, removing concept1 and adding concept2.

@kriskelly what is your take?

**Comment by kriskelly** [comment]
I might need some context in order to give an informed opinion. What is the proposed change, why is it being made, why is it a high priority (when Quill-Grammar has so many other bugs, etc). 




Otherwise yeah, generally just pass the UID along, and I don't have an opinion about the number of queries made.

**Comment by marcellosachs** [comment]
I agree that this is not a high priority right now. I think we're talking about it now to give technical feedback to peter and elliot, who are working on specs for the content editor. In terms of development time, I believe we're indeed focusing on getting QG production ready.

Now that I think about it, which technical strategy is pursued (querying for 0 level concepts on an if-needed basis vs. hard-coding associations on the lms) would have no bearing on what the product can do or how it functions (including the cms), so we should be able to remain agnostic about that technical decision until we actually have to implement it (at which point I can perhaps provide a better explanation of the problem / potential strategies).

**Comment by kriskelly** [comment]
Based on recent discussion, we decided to remove the `concepts` list from the JSON body. This means there is no association of activities to concepts right now.

**Comment by kriskelly** [comment]
Moved to empirical-org/Empirical-Core#830.
