### ISSUE TITLE
Not reporting scores to LMS

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Quill-Grammar#95]

**Comment by marcellosachs** [comment]
split out from #82

**Comment by marcellosachs** [comment]
I believe kris is currently working on this, as its related to oauth

**Comment by kriskelly** [comment]
@marcellosachs @petergault This is only broken because somebody (Marcello?) changed the concept tag reporting to send a 'concept_id' instead of the concept tag name, so the LMS would need to be updated before this will work properly. What I would do is just revert that change, but I'm not sure if that will break something else. We should talk about it. It's not actually related to OAuth at all.

**Comment by kriskelly** [comment]
Actually the app still doesn't report scores from the proofreading portion. Need to dive into this a bit more to figure out why.
